services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=${DB_NEO4J_USER}/${DB_NEO4J_PASS}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_default__database=${DB_NEO4J_NAME}
      - NEO4J_PLUGINS=["apoc", "graph-data-science", "bloom"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
    ports:
      - ${DB_NEO4J_PORT_ADMIN}:7474
      - ${DB_NEO4J_PORT_BOLT}:7687
    networks:
      - db_network
    healthcheck:
      test: wget http://localhost:${DB_NEO4J_PORT_BOLT} || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  fast_api_app:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: fast_api_app_container
    restart: always
    env_file:
      - .env.docker
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - .:/docker_app
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    networks:
      - db_network
    command: python -m uvicorn core.app:app --host 0.0.0.0 --port ${HTTP_PORT}

networks:
  db_network:
    driver: bridge